"""
Script de auditoria histórico (não faz parte do app em execução).
Os achados deste script já estão consolidados em docs/MANUAL_TECNICO.md
(seção 8 — Resumo da auditoria de dados). Mantido apenas como referência
das queries originais usadas na primeira rodada de auditoria.
"""
import sys
sys.path.insert(0, r'C:\Users\ferod\OneDrive\Desktop\Projeto-Cetel')
from core.data.firebird import fb_query
import pandas as pd
import traceback

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

results = {}

def run_query(label, sql):
    """Executa `sql` no Firebird, imprime o resultado no console e guarda em `results[label]` (status + DataFrame)."""
    print(f"\n{'='*60}")
    print(f"=== {label} ===")
    print(f"{'='*60}")
    try:
        df = fb_query(sql)
        print(df.to_string())
        results[label] = {'status': 'OK', 'data': df}
        return df
    except Exception as e:
        msg = str(e)
        print(f"ERRO: {msg}")
        traceback.print_exc()
        results[label] = {'status': 'ERRO', 'error': msg}
        return None

# 1. FINANCEIRO — AR total em aberto
run_query("1. AR TOTAL EM ABERTO",
    "SELECT SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS TOTAL_AR, COUNT(*) AS QTD FROM DOCUREC WHERE SITUACAO = '1'")

# 2. FINANCEIRO — AP total em aberto
run_query("2. AP TOTAL EM ABERTO",
    "SELECT SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS TOTAL_AP, COUNT(*) AS QTD FROM DOCUPAG WHERE SITUACAO = '1'")

# 3. FINANCEIRO — Saldo bancário
run_query("3. SALDO BANCARIO",
    "SELECT TRIM(CODBANCO) AS BCO, TRIM(CONTA), MAX(DATAMOV) AS ULT_MOV, SUM(VLRSALDO) AS SALDO_TOT FROM MOVIBAN WHERE (ESTORNADO IS NULL OR ESTORNADO <> 'S') GROUP BY 1, 2 ORDER BY 1")

# 4. FINANCEIRO — AR vencido
run_query("4. AR VENCIDO",
    "SELECT SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS VENCIDO_AR, COUNT(*) AS QTD FROM DOCUREC WHERE SITUACAO = '1' AND DT_VENCIMENTO < CAST('NOW' AS TIMESTAMP)")

# 5. FINANCEIRO — AP vencido
run_query("5. AP VENCIDO",
    "SELECT SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS VENCIDO_AP, COUNT(*) AS QTD FROM DOCUPAG WHERE SITUACAO = '1' AND DT_VENCIMENTO < CAST('NOW' AS TIMESTAMP)")

# 6. COMERCIAL — Faturamento mensal 2026
run_query("6. FATURAMENTO MENSAL 2026 (mar-jun)",
    "SELECT EXTRACT(MONTH FROM DATAFATURA) AS MES, SUM(TOTALPEDIDO) AS FAT, COUNT(*) AS QTD FROM PEDIDOC WHERE TRIM(FATURADO)='S' AND DATAFATURA >= CAST('2026-03-01' AS TIMESTAMP) AND DATAFATURA < CAST('2026-07-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 1")

# 6b. Faturamento completo 2026
run_query("6b. FATURAMENTO COMPLETO 2026",
    "SELECT EXTRACT(MONTH FROM DATAFATURA) AS MES, SUM(TOTALPEDIDO) AS FAT, COUNT(*) AS QTD FROM PEDIDOC WHERE TRIM(FATURADO)='S' AND DATAFATURA >= CAST('2026-01-01' AS TIMESTAMP) AND DATAFATURA < CAST('2027-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 1")

# 7. ESTOQUE — SKUs e valor
run_query("7. ESTOQUE TOTAL",
    "SELECT COUNT(*) AS TOTAL_SKUS, SUM(CASE WHEN ESTOQUE > 0 THEN 1 ELSE 0 END) AS COM_ESTOQUE, SUM(ESTOQUE * PRECOCUSTO) AS VALOR_CUSTO FROM COMPPROD WHERE TRIM(CODEMPRESA)='00'")

# 8. COMPRAS — NF entrada 2026
run_query("8. COMPRAS 2026 (NF ENTRADA)",
    "SELECT COUNT(DISTINCT NUMERONF) AS QTD_NF, COUNT(DISTINCT CODFORNEC) AS QTD_FORN, SUM(VLTOTAL) AS TOTAL FROM NFENTRC WHERE DTENTRADA >= CAST('2026-01-01' AS TIMESTAMP) AND DTENTRADA < CAST('2026-07-01' AS TIMESTAMP)")

# 9. ESTOQUE — Top grupos
run_query("9. TOP GRUPOS ESTOQUE",
    "SELECT TRIM(g.DESCRICAO) AS GRUPO, COUNT(p.CODPROD) AS SKUS, SUM(p.ESTOQUE * p.PRECOCUSTO) AS VALOR FROM COMPPROD p JOIN GRUPROD g ON TRIM(g.CODGRUPO) = TRIM(p.CODGRUPO) WHERE TRIM(p.CODEMPRESA)='00' AND p.ESTOQUE > 0 GROUP BY 1 ORDER BY 3 DESC")

# 10. CLIENTES — Total
run_query("10a. TOTAL CLIENTES",
    "SELECT COUNT(*) AS TOTAL_CLIENTES FROM CLIENTE")

run_query("10b. CLIENTES ATIVOS 2026",
    "SELECT COUNT(DISTINCT CODCLIENTE) AS ATIVOS_2026 FROM PEDIDOC WHERE TRIM(FATURADO)='S' AND DATAFATURA >= CAST('2026-01-01' AS TIMESTAMP)")

# 11. VENDEDORES — Faturamento 2026
run_query("11. FAT POR VENDEDOR 2026",
    "SELECT TRIM(CODVEND) AS VEND, SUM(TOTALPEDIDO) AS FAT FROM PEDIDOC WHERE TRIM(FATURADO)='S' AND DATAFATURA >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 2 DESC")

# 12. ALERTAS — AR crítico >90 dias
run_query("12. AR CRITICO >90 DIAS",
    "SELECT COUNT(DISTINCT CODCLIENTE) AS N_CLIENTES, SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS VALOR FROM DOCUREC WHERE SITUACAO='1' AND CAST('NOW' AS TIMESTAMP) - DT_VENCIMENTO > 90")

# 13. PDV — MVGERAL tipo 55
run_query("13. PDV MVGERAL (TIPO 55) 2026",
    "SELECT EXTRACT(MONTH FROM DT_MOVIMENTO) AS MES, SUM(QUANTIDADE * PRECOVENDA) AS FAT_PDV, COUNT(*) AS QTD FROM MVGERAL WHERE TRIM(TIPOMOV)='55' AND DT_MOVIMENTO >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 1")

# 14. PMR proxy
run_query("14. PMR PROXY (DIAS MEDIO EMISSAO)",
    "SELECT AVG(CAST('NOW' AS TIMESTAMP) - DT_EMISSAO) AS DIAS_MEDIO_EMISSAO FROM DOCUREC WHERE SITUACAO='1' AND DT_EMISSAO IS NOT NULL")

# 15. Top fornecedores 2026
run_query("15. TOP FORNECEDORES 2026",
    "SELECT TRIM(f.FORNECEDOR) AS FORN, SUM(n.VLTOTAL) AS TOTAL FROM NFENTRC n JOIN FORNECE f ON TRIM(f.CODFORNEC) = TRIM(n.CODFORNEC) WHERE n.DTENTRADA >= CAST('2026-01-01' AS TIMESTAMP) AND n.DTENTRADA < CAST('2026-07-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 2 DESC")

# =====================================================
# QUERIES EXTRAS — tabelas potencialmente ignoradas
# =====================================================

# 16. MVGERAL — outros tipos de movimento
run_query("16. MVGERAL TIPOS DISTINTOS",
    "SELECT TRIM(TIPOMOV) AS TIPO, COUNT(*) AS QTD, SUM(QUANTIDADE * PRECOVENDA) AS VALOR FROM MVGERAL WHERE DT_MOVIMENTO >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 2 DESC")

# 17. PEDIDOC — pedidos em aberto (nao faturados)
run_query("17. PEDIDOS EM ABERTO (NAO FATURADOS)",
    "SELECT COUNT(*) AS QTD, SUM(TOTALPEDIDO) AS VALOR FROM PEDIDOC WHERE TRIM(FATURADO)<>'S'")

# 18. COMISSAO — se existe
run_query("18. COMISSAO VENDEDORES 2026",
    "SELECT TRIM(CODVEND) AS VEND, SUM(VLCOMISSAO) AS COMISSAO FROM COMISSAO WHERE DTREF >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 2 DESC")

# 19. CAIXA — movimentos de caixa
run_query("19. CAIXA MOVIMENTOS 2026",
    "SELECT EXTRACT(MONTH FROM DTMOV) AS MES, SUM(CASE WHEN TPMOV='E' THEN VLMOV ELSE 0 END) AS ENTRADA, SUM(CASE WHEN TPMOV='S' THEN VLMOV ELSE 0 END) AS SAIDA FROM MOVCAIXA WHERE DTMOV >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 1")

# 20. NFENTRC — itens NF entrada top produtos
run_query("20. TOP PRODUTOS COMPRADOS 2026",
    "SELECT TRIM(i.CODPROD) AS PROD, SUM(i.QTDE) AS QTD_COMPRADA, SUM(i.VLTOTAL) AS VALOR FROM NFENTRCI i JOIN NFENTRC n ON n.NUMERONF = i.NUMERONF AND TRIM(n.CODFORNEC) = TRIM(i.CODFORNEC) WHERE n.DTENTRADA >= CAST('2026-01-01' AS TIMESTAMP) GROUP BY 1 ORDER BY 3 DESC")

# 21. Checar DOCUREC colunas
run_query("21. DOCUREC AMOSTRA (5 linhas)",
    "SELECT FIRST 5 * FROM DOCUREC WHERE SITUACAO='1'")

# 22. Checar DOCUPAG colunas
run_query("22. DOCUPAG AMOSTRA (5 linhas)",
    "SELECT FIRST 5 * FROM DOCUPAG WHERE SITUACAO='1'")

# 23. Fluxo de caixa projetado — AR+AP juntos
run_query("23. FLUXO PROJETADO (AR por vencimento)",
    "SELECT EXTRACT(MONTH FROM DT_VENCIMENTO) AS MES, EXTRACT(YEAR FROM DT_VENCIMENTO) AS ANO, SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS VALOR, COUNT(*) AS QTD FROM DOCUREC WHERE SITUACAO='1' AND DT_VENCIMENTO >= CAST('2026-01-01' AS TIMESTAMP) AND DT_VENCIMENTO < CAST('2027-01-01' AS TIMESTAMP) GROUP BY 1, 2 ORDER BY 2, 1")

run_query("24. FLUXO PROJETADO (AP por vencimento)",
    "SELECT EXTRACT(MONTH FROM DT_VENCIMENTO) AS MES, EXTRACT(YEAR FROM DT_VENCIMENTO) AS ANO, SUM(VALORDOCTO - COALESCE(VALORPAGO,0)) AS VALOR, COUNT(*) AS QTD FROM DOCUPAG WHERE SITUACAO='1' AND DT_VENCIMENTO >= CAST('2026-01-01' AS TIMESTAMP) AND DT_VENCIMENTO < CAST('2027-01-01' AS TIMESTAMP) GROUP BY 1, 2 ORDER BY 2, 1")

# 25. Verificar NATUREZA / PLANCONTAS
run_query("25. PLANO DE CONTAS (AMOSTRA)",
    "SELECT FIRST 20 * FROM PLANCONTAS ORDER BY CODCONTA")

# 26. NFENTRC colunas amostra
run_query("26. NFENTRC AMOSTRA (3 linhas 2026)",
    "SELECT FIRST 3 * FROM NFENTRC WHERE DTENTRADA >= CAST('2026-01-01' AS TIMESTAMP)")

print("\n\n" + "="*60)
print("=== RESUMO FINAL ===")
print("="*60)
for label, res in results.items():
    status = res['status']
    if status == 'OK':
        df = res['data']
        print(f"[OK]   {label}: {len(df)} linha(s)")
    else:
        print(f"[ERRO] {label}: {res['error'][:80]}")
